### ISSUE TITLE
короч

### ISSUE THREAD

**Issue by savolkov** [Elbidor/Sign-In#1]
https://github.com/Elbidor/Sign-In/blob/08e166182d7da7038ffc61e6daf362eda2a4225d/index.html#L12

туточки нужно лучше вынести js в отдельный файл тк смешивание js и верстки в кучу -- плохая практика

а еще чтобы не геморроиться с DOM можно юзать jQuery

**Comment by Elbidor** [comment]
Ну, потом как-нибудь

**Comment by savolkov** [comment]
@Elbidor главное в таком виде не сдай

**Comment by Elbidor** [comment]
Вроде сделал, хз

**Comment by savolkov** [comment]
Православно.
